apiVersion: v1
kind: Secret

metadata:
  name: boutique-secret
  namespace: default

type: Opaque

data:
  # Remplacez ces valeurs par vos propres valeurs encodées en base64
  DB_USER: YWRtaW4=
  DB_PASSWORD: cGFzc3dvcmQxMjM=
